name: Check UI Deployment
description: Check if React UI needs deployment based on source hash comparison

inputs:
  stack-name:
    description: 'CloudFormation stack name'
    required: true

outputs:
  skip_ui:
    description: 'Whether UI deployment should be skipped (true/false)'
    value: ${{ steps.check.outputs.skip_ui }}

runs:
  using: composite
  steps:
    - name: Check if UI needs deployment
      id: check
      shell: bash
      run: |
        STACK_NAME="${{ inputs.stack-name }}"

        # Get UI bucket from stack outputs
        UI_BUCKET=$(aws cloudformation describe-stacks \
          --stack-name "${STACK_NAME}" \
          --query 'Stacks[0].Outputs[?OutputKey==`UiBucketName`].OutputValue' \
          --output text 2>/dev/null || echo "")

        if [ -z "$UI_BUCKET" ]; then
          echo "⚠️ Could not find UI bucket, will deploy UI"
          echo "skip_ui=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Check if bucket has index.html
        if aws s3 ls "s3://${UI_BUCKET}/index.html" >/dev/null 2>&1; then
          echo "✅ UI already deployed in bucket ${UI_BUCKET}"

          # Calculate hash of UI source to detect changes
          UI_HASH=$(find ui/src ui/public ui/index.html -type f -exec md5sum {} \; 2>/dev/null | sort | md5sum | cut -d' ' -f1)

          # Try to get stored hash from S3
          STORED_HASH=$(aws s3 cp "s3://${UI_BUCKET}/.ui-hash" - 2>/dev/null || echo "")

          if [ "${UI_HASH}" = "${STORED_HASH}" ]; then
            echo "✅ UI source unchanged (hash: ${UI_HASH}), skipping rebuild"
            echo "skip_ui=true" >> $GITHUB_OUTPUT
          else
            echo "UI source changed (${UI_HASH} vs ${STORED_HASH}), will deploy"
            echo "skip_ui=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "UI not found in bucket, will deploy"
          echo "skip_ui=false" >> $GITHUB_OUTPUT
        fi
