AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Silvermoat Compute Stack - IAM roles and Lambda functions

Parameters:
  AppName:
    Type: String
    Description: "Short app name used in resource naming"

  StageName:
    Type: String
    Description: "Stage name for the application"

  QuotesTableArn:
    Type: String
    Description: "ARN of the Quotes DynamoDB table"

  PoliciesTableArn:
    Type: String
    Description: "ARN of the Policies DynamoDB table"

  ClaimsTableArn:
    Type: String
    Description: "ARN of the Claims DynamoDB table"

  PaymentsTableArn:
    Type: String
    Description: "ARN of the Payments DynamoDB table"

  CasesTableArn:
    Type: String
    Description: "ARN of the Cases DynamoDB table"

  QuotesTableName:
    Type: String
    Description: "Name of the Quotes DynamoDB table"

  PoliciesTableName:
    Type: String
    Description: "Name of the Policies DynamoDB table"

  ClaimsTableName:
    Type: String
    Description: "Name of the Claims DynamoDB table"

  PaymentsTableName:
    Type: String
    Description: "Name of the Payments DynamoDB table"

  CasesTableName:
    Type: String
    Description: "Name of the Cases DynamoDB table"

  UiBucketArn:
    Type: String
    Description: "ARN of the UI S3 bucket"

  UiBucketName:
    Type: String
    Description: "Name of the UI S3 bucket"

  DocsBucketArn:
    Type: String
    Description: "ARN of the Docs S3 bucket"

  DocsBucketName:
    Type: String
    Description: "Name of the Docs S3 bucket"

  SnsTopicArn:
    Type: String
    Description: "ARN of the SNS topic"

  LambdaCodeS3Bucket:
    Type: String
    Description: "S3 bucket containing Lambda deployment packages"

  MvpServiceCodeS3Key:
    Type: String
    Description: "S3 key for MVP service Lambda deployment package"

  SeederCodeS3Key:
    Type: String
    Description: "S3 key for seeder Lambda deployment package"

  UiBucketWebsiteURL:
    Type: String
    Description: "UI bucket website URL for seeder function"

Resources:
  # ----------------------------
  # IAM Role for MVP Lambda
  # ----------------------------
  MvpLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${AppName}-${StageName}-mvp-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: Logs
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

              - Sid: DynamoRW
                Effect: Allow
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:DeleteItem"
                  - "dynamodb:Scan"
                Resource:
                  - !Ref QuotesTableArn
                  - !Ref PoliciesTableArn
                  - !Ref ClaimsTableArn
                  - !Ref PaymentsTableArn
                  - !Ref CasesTableArn

              - Sid: S3DocsList
                Effect: Allow
                Action: "s3:ListBucket"
                Resource: !Ref DocsBucketArn

              - Sid: S3DocsObjRW
                Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:DeleteObject"
                Resource: !Sub "${DocsBucketArn}/*"

              - Sid: PutEvents
                Effect: Allow
                Action: "events:PutEvents"
                Resource: "*"

              - Sid: PublishSNS
                Effect: Allow
                Action: "sns:Publish"
                Resource: !Ref SnsTopicArn

              - Sid: BedrockInvoke
                Effect: Allow
                Action:
                  - "bedrock:InvokeModel"
                Resource:
                  - !Sub "arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0"

  # ----------------------------
  # MVP Service Lambda (single function; routes by path)
  # ----------------------------
  MvpServiceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: handler.handler
      Role: !GetAtt MvpLambdaRole.Arn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          QUOTES_TABLE: !Ref QuotesTableName
          POLICIES_TABLE: !Ref PoliciesTableName
          CLAIMS_TABLE: !Ref ClaimsTableName
          PAYMENTS_TABLE: !Ref PaymentsTableName
          CASES_TABLE: !Ref CasesTableName
          DOCS_BUCKET: !Ref DocsBucketName
          SNS_TOPIC_ARN: !Ref SnsTopicArn
          BEDROCK_MODEL_ID: anthropic.claude-3-5-sonnet-20240620-v1:0
          BEDROCK_REGION: !Ref AWS::Region
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref MvpServiceCodeS3Key

  # ----------------------------
  # Seeder Lambda (Custom Resource): seeds UI + demo data; cleans on delete
  # ----------------------------
  SeederLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${AppName}-${StageName}-seeder-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: Logs
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

              - Sid: S3ListBuckets
                Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:ListBucketVersions"
                Resource:
                  - !Ref UiBucketArn
                  - !Ref DocsBucketArn

              - Sid: S3Objects
                Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:DeleteObject"
                  - "s3:DeleteObjectVersion"
                Resource:
                  - !Sub "${UiBucketArn}/*"
                  - !Sub "${DocsBucketArn}/*"

              - Sid: DynamoSeedAndCleanup
                Effect: Allow
                Action:
                  - "dynamodb:PutItem"
                  - "dynamodb:Scan"
                  - "dynamodb:DeleteItem"
                Resource:
                  - !Ref QuotesTableArn
                  - !Ref PoliciesTableArn
                  - !Ref ClaimsTableArn
                  - !Ref PaymentsTableArn
                  - !Ref CasesTableArn

  SeederFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: handler.handler
      Role: !GetAtt SeederLambdaRole.Arn
      Timeout: 120
      MemorySize: 256
      Environment:
        Variables:
          UI_BUCKET: !Ref UiBucketName
          DOCS_BUCKET: !Ref DocsBucketName
          QUOTES_TABLE: !Ref QuotesTableName
          POLICIES_TABLE: !Ref PoliciesTableName
          CLAIMS_TABLE: !Ref ClaimsTableName
          PAYMENTS_TABLE: !Ref PaymentsTableName
          CASES_TABLE: !Ref CasesTableName
          WEB_BASE: !Ref UiBucketWebsiteURL
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref SeederCodeS3Key

Outputs:
  MvpServiceFunctionArn:
    Description: "ARN of the MVP service Lambda function"
    Value: !GetAtt MvpServiceFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-MvpServiceFunctionArn"

  MvpServiceFunctionName:
    Description: "Name of the MVP service Lambda function"
    Value: !Ref MvpServiceFunction
    Export:
      Name: !Sub "${AWS::StackName}-MvpServiceFunctionName"

  SeederFunctionArn:
    Description: "ARN of the seeder Lambda function"
    Value: !GetAtt SeederFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SeederFunctionArn"
