AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Silvermoat Storage Stack - S3 buckets for UI website and documents

Resources:
  # ----------------------------
  # S3 Buckets (UI Website + Docs)
  # ----------------------------
  UiBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Public website hosting requires public access.
      # Keep this ONLY for demo environments.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      VersioningConfiguration:
        Status: Suspended

  UiBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UiBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadForWebsite
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${UiBucket.Arn}/*"

  DocsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Docs/media should remain private (Lambda only)
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Suspended

Outputs:
  UiBucketName:
    Description: "Name of the UI S3 bucket"
    Value: !Ref UiBucket
    Export:
      Name: !Sub "${AWS::StackName}-UiBucketName"

  UiBucketArn:
    Description: "ARN of the UI S3 bucket"
    Value: !GetAtt UiBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-UiBucketArn"

  UiBucketWebsiteURL:
    Description: "Website URL of the UI S3 bucket"
    Value: !GetAtt UiBucket.WebsiteURL
    Export:
      Name: !Sub "${AWS::StackName}-UiBucketWebsiteURL"

  UiBucketWebsiteDomain:
    Description: "Website domain of the UI S3 bucket (for CloudFront origin)"
    Value: !Select [2, !Split ["/", !GetAtt UiBucket.WebsiteURL]]
    Export:
      Name: !Sub "${AWS::StackName}-UiBucketWebsiteDomain"

  DocsBucketName:
    Description: "Name of the Docs S3 bucket"
    Value: !Ref DocsBucket
    Export:
      Name: !Sub "${AWS::StackName}-DocsBucketName"

  DocsBucketArn:
    Description: "ARN of the Docs S3 bucket"
    Value: !GetAtt DocsBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-DocsBucketArn"
