AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Silvermoat Insurance - One-shot deployable MVP (CloudFormation with nested stacks).
  Parent stack orchestrates data, storage, compute, API, and frontend nested stacks.
  Custom Resources for seeding/cleanup remain in parent stack.

Parameters:
  AppName:
    Type: String
    Default: silvermoat
    Description: "Short app name used in resource naming."

  StageName:
    Type: String
    Default: demo
    AllowedPattern: "^[a-zA-Z0-9_-]+$"
    Description: "API Gateway stage name."

  ApiDeploymentToken:
    Type: String
    Default: "v1"
    Description: >
      Change this value to force a new API Gateway deployment on updates
      (e.g., v2, v3...). Helps avoid 'API didn't update' confusion.

  UiSeedingMode:
    Type: String
    Default: "seeded"
    AllowedValues:
      - "seeded"
      - "external"
    Description: >
      "seeded" = Lambda uploads simple index.html (default for quick demo).
      "external" = UI is deployed separately (e.g., React SPA via deploy-ui.sh).
      When "external", skip index.html upload in seed mode.

  DomainName:
    Type: String
    Default: "silvermoat.net"
    Description: >
      Custom domain for CloudFront (default: silvermoat.net).
      Set to empty string ("") to disable custom domain and use only CloudFront default domain.
      To use custom domain: deploy stack, add DNS validation CNAME to Cloudflare,
      wait for cert validation, then add CloudFront alias CNAME to Cloudflare.

  CreateCloudFront:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: >
      Create CloudFront distribution (default: true).
      Set to "false" for ephemeral test stacks to use S3 website URL directly (HTTP).
      Production stacks should use "true" for HTTPS via CloudFront.

  LambdaCodeS3Bucket:
    Type: String
    Description: >
      S3 bucket containing Lambda deployment packages and nested stack templates.
      Typically the same bucket used for CloudFormation templates.

  MvpServiceCodeS3Key:
    Type: String
    Default: "lambda/mvp-service.zip"
    Description: S3 key for MVP service Lambda deployment package

  SeederCodeS3Key:
    Type: String
    Default: "lambda/seeder.zip"
    Description: S3 key for seeder Lambda deployment package

Conditions:
  ShouldCreateCloudFront: !Equals [!Ref CreateCloudFront, "true"]

Resources:
  # ----------------------------
  # Nested Stack: Data Layer (DynamoDB + SNS)
  # ----------------------------
  DataStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${LambdaCodeS3Bucket}.s3.amazonaws.com/nested/data-stack.yaml"
      Parameters:
        AppName: !Ref AppName
        StageName: !Ref StageName
      Tags:
        - Key: NestedStack
          Value: DataStack

  # ----------------------------
  # Nested Stack: Storage Layer (S3 Buckets)
  # ----------------------------
  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${LambdaCodeS3Bucket}.s3.amazonaws.com/nested/storage-stack.yaml"
      Tags:
        - Key: NestedStack
          Value: StorageStack

  # ----------------------------
  # Nested Stack: Compute Layer (Lambda Functions + IAM)
  # ----------------------------
  ComputeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - DataStack
      - StorageStack
    Properties:
      TemplateURL: !Sub "https://${LambdaCodeS3Bucket}.s3.amazonaws.com/nested/compute-stack.yaml"
      Parameters:
        AppName: !Ref AppName
        StageName: !Ref StageName
        QuotesTableArn: !GetAtt DataStack.Outputs.QuotesTableArn
        PoliciesTableArn: !GetAtt DataStack.Outputs.PoliciesTableArn
        ClaimsTableArn: !GetAtt DataStack.Outputs.ClaimsTableArn
        PaymentsTableArn: !GetAtt DataStack.Outputs.PaymentsTableArn
        CasesTableArn: !GetAtt DataStack.Outputs.CasesTableArn
        QuotesTableName: !GetAtt DataStack.Outputs.QuotesTableName
        PoliciesTableName: !GetAtt DataStack.Outputs.PoliciesTableName
        ClaimsTableName: !GetAtt DataStack.Outputs.ClaimsTableName
        PaymentsTableName: !GetAtt DataStack.Outputs.PaymentsTableName
        CasesTableName: !GetAtt DataStack.Outputs.CasesTableName
        UiBucketArn: !GetAtt StorageStack.Outputs.UiBucketArn
        UiBucketName: !GetAtt StorageStack.Outputs.UiBucketName
        DocsBucketArn: !GetAtt StorageStack.Outputs.DocsBucketArn
        DocsBucketName: !GetAtt StorageStack.Outputs.DocsBucketName
        SnsTopicArn: !GetAtt DataStack.Outputs.SnsTopicArn
        LambdaCodeS3Bucket: !Ref LambdaCodeS3Bucket
        MvpServiceCodeS3Key: !Ref MvpServiceCodeS3Key
        SeederCodeS3Key: !Ref SeederCodeS3Key
        UiBucketWebsiteURL: !GetAtt StorageStack.Outputs.UiBucketWebsiteURL
      Tags:
        - Key: NestedStack
          Value: ComputeStack

  # ----------------------------
  # Nested Stack: API Gateway
  # ----------------------------
  ApiStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ComputeStack
    Properties:
      TemplateURL: !Sub "https://${LambdaCodeS3Bucket}.s3.amazonaws.com/nested/api-stack.yaml"
      Parameters:
        AppName: !Ref AppName
        StageName: !Ref StageName
        ApiDeploymentToken: !Ref ApiDeploymentToken
        MvpServiceFunctionArn: !GetAtt ComputeStack.Outputs.MvpServiceFunctionArn
        MvpServiceFunctionName: !GetAtt ComputeStack.Outputs.MvpServiceFunctionName
      Tags:
        - Key: NestedStack
          Value: ApiStack

  # ----------------------------
  # Nested Stack: Frontend (CloudFront + ACM)
  # ----------------------------
  FrontendStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: StorageStack
    Properties:
      TemplateURL: !Sub "https://${LambdaCodeS3Bucket}.s3.amazonaws.com/nested/frontend-stack.yaml"
      Parameters:
        DomainName: !Ref DomainName
        CreateCloudFront: !Ref CreateCloudFront
        UiBucketWebsiteDomain: !GetAtt StorageStack.Outputs.UiBucketWebsiteDomain
      Tags:
        - Key: NestedStack
          Value: FrontendStack

  # ----------------------------
  # Custom Resources (seeding and cleanup)
  # Remain in parent stack for orchestration
  # ----------------------------
  SeedCustomResource:
    Type: AWS::CloudFormation::CustomResource
    DependsOn:
      - ApiStack
      - StorageStack
    Properties:
      ServiceToken: !GetAtt ComputeStack.Outputs.SeederFunctionArn
      Mode: seed
      UiSeedingMode: !Ref UiSeedingMode
      ApiBaseUrl: !GetAtt ApiStack.Outputs.ApiBaseUrl

  CleanupCustomResource:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: StorageStack
    Properties:
      ServiceToken: !GetAtt ComputeStack.Outputs.SeederFunctionArn
      Mode: cleanup

Outputs:
  WebUrl:
    Description: "S3 Website URL (HTTP) - Use CloudFrontUrl for production, or this for test stacks"
    Value: !GetAtt StorageStack.Outputs.UiBucketWebsiteURL

  CloudFrontUrl:
    Condition: ShouldCreateCloudFront
    Description: "CloudFront distribution URL (HTTPS) - Primary access method"
    Value: !GetAtt FrontendStack.Outputs.CloudFrontUrl

  CloudFrontDomain:
    Condition: ShouldCreateCloudFront
    Description: "CloudFront domain name (for DNS CNAME record)"
    Value: !GetAtt FrontendStack.Outputs.CloudFrontDomain

  CustomDomainUrl:
    Condition: ShouldCreateCloudFront
    Description: "Custom domain URL (if DomainName parameter provided and CloudFront enabled)"
    Value: !GetAtt FrontendStack.Outputs.CustomDomainUrl

  CertificateArn:
    Condition: ShouldCreateCloudFront
    Description: "ACM certificate ARN (for reference)"
    Value: !GetAtt FrontendStack.Outputs.CertificateArn

  ApiBaseUrl:
    Description: "API base URL (HTTPS)"
    Value: !GetAtt ApiStack.Outputs.ApiBaseUrl

  UiBucketName:
    Value: !GetAtt StorageStack.Outputs.UiBucketName

  DocsBucketName:
    Value: !GetAtt StorageStack.Outputs.DocsBucketName

  QuotesTableName:
    Value: !GetAtt DataStack.Outputs.QuotesTableName
  PoliciesTableName:
    Value: !GetAtt DataStack.Outputs.PoliciesTableName
  ClaimsTableName:
    Value: !GetAtt DataStack.Outputs.ClaimsTableName
  PaymentsTableName:
    Value: !GetAtt DataStack.Outputs.PaymentsTableName
  CasesTableName:
    Value: !GetAtt DataStack.Outputs.CasesTableName

  DemoNotificationsTopicArn:
    Value: !GetAtt DataStack.Outputs.SnsTopicArn
