name: Install Dependencies
description: Install Python test dependencies and UI npm packages

inputs:
  install-ui:
    description: 'Whether to install UI dependencies'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Install system dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y graphviz

    - name: Install Python test dependencies
      shell: bash
      run: pip install -r requirements-test.txt

    - name: Install UI dependencies
      if: ${{ inputs.install-ui == 'true' }}
      shell: bash
      working-directory: ui-insurance
      run: npm ci
