name: Detect Changes
description: Detect infrastructure, UI, and test file changes using git diff

inputs:
  base_sha:
    description: 'Base SHA for comparison (optional, auto-detected from context)'
    required: false
  head_sha:
    description: 'Head SHA for comparison (optional, auto-detected from context)'
    required: false
  force_deploy:
    description: 'Force deploy everything (for workflow_dispatch)'
    required: false
    default: 'false'

outputs:
  infrastructure:
    description: 'Whether global infrastructure files changed (true/false)'
    value: ${{ steps.detect.outputs.infrastructure }}
  insurance_lambda_changed:
    description: 'Whether insurance Lambda files changed (true/false)'
    value: ${{ steps.detect.outputs.insurance_lambda_changed }}
  retail_lambda_changed:
    description: 'Whether retail Lambda files changed (true/false)'
    value: ${{ steps.detect.outputs.retail_lambda_changed }}
  healthcare_lambda_changed:
    description: 'Whether healthcare Lambda files changed (true/false)'
    value: ${{ steps.detect.outputs.healthcare_lambda_changed }}
  landing_lambda_changed:
    description: 'Whether landing Lambda files changed (true/false)'
    value: ${{ steps.detect.outputs.landing_lambda_changed }}
  ui:
    description: 'Whether global UI files changed (true/false)'
    value: ${{ steps.detect.outputs.ui }}
  insurance_ui_changed:
    description: 'Whether insurance UI files changed (true/false)'
    value: ${{ steps.detect.outputs.insurance_ui_changed }}
  retail_ui_changed:
    description: 'Whether retail UI files changed (true/false)'
    value: ${{ steps.detect.outputs.retail_ui_changed }}
  healthcare_ui_changed:
    description: 'Whether healthcare UI files changed (true/false)'
    value: ${{ steps.detect.outputs.healthcare_ui_changed }}
  landing_ui_changed:
    description: 'Whether landing UI files changed (true/false)'
    value: ${{ steps.detect.outputs.landing_ui_changed }}
  tests:
    description: 'Whether test files changed (true/false)'
    value: ${{ steps.detect.outputs.tests }}
  # Legacy aliases for backwards compatibility
  infrastructure_changed:
    description: 'Alias for infrastructure (backwards compatibility)'
    value: ${{ steps.detect.outputs.infrastructure }}
  ui_changed:
    description: 'Alias for ui (backwards compatibility)'
    value: ${{ steps.detect.outputs.ui }}

runs:
  using: composite
  steps:
    - name: Detect file changes
      id: detect
      shell: bash
      run: |
        # Force deploy mode (workflow_dispatch)
        if [ "${{ inputs.force_deploy }}" = "true" ]; then
          echo "🚀 Force deploy mode - deploying all components"
          echo "infrastructure=true" >> $GITHUB_OUTPUT
          echo "ui=true" >> $GITHUB_OUTPUT
          echo "tests=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Determine comparison strategy based on context
        if [ -n "${{ github.event.pull_request.number }}" ]; then
          # Active PR: compare base and head
          echo "Analyzing changes in PR #${{ github.event.pull_request.number }}"
          BASE_SHA="${{ inputs.base_sha || github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ inputs.head_sha || github.sha }}"
          echo "Comparing ${BASE_SHA:0:7}..${HEAD_SHA:0:7}"
          CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA)
        elif [ "${{ github.event_name }}" = "pull_request" ]; then
          # Merged PR: use git diff-tree on merge commit
          echo "Analyzing changes in merge commit ${{ github.event.pull_request.merge_commit_sha || github.sha }}"
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)
        else
          # Manual dispatch or other: use git diff-tree
          echo "Analyzing changes in commit ${{ github.sha }}"
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)
        fi

        echo "Changed files:"
        echo "$CHANGED_FILES"
        echo ""

        # Global infrastructure changes (CDK, shared scripts)
        if echo "$CHANGED_FILES" | grep -E '^(cdk/|scripts/deploy-stack\.sh)'; then
          echo "infrastructure=true" >> $GITHUB_OUTPUT
          echo "✅ Global infrastructure files changed"
        else
          echo "infrastructure=false" >> $GITHUB_OUTPUT
          echo "ℹ️ No global infrastructure changes"
        fi

        # Per-vertical Lambda changes
        if echo "$CHANGED_FILES" | grep -E '^lambda/insurance/'; then
          echo "insurance_lambda_changed=true" >> $GITHUB_OUTPUT
          echo "✅ Insurance Lambda changed"
        else
          echo "insurance_lambda_changed=false" >> $GITHUB_OUTPUT
        fi

        if echo "$CHANGED_FILES" | grep -E '^lambda/retail/'; then
          echo "retail_lambda_changed=true" >> $GITHUB_OUTPUT
          echo "✅ Retail Lambda changed"
        else
          echo "retail_lambda_changed=false" >> $GITHUB_OUTPUT
        fi

        if echo "$CHANGED_FILES" | grep -E '^lambda/healthcare/'; then
          echo "healthcare_lambda_changed=true" >> $GITHUB_OUTPUT
          echo "✅ Healthcare Lambda changed"
        else
          echo "healthcare_lambda_changed=false" >> $GITHUB_OUTPUT
        fi

        if echo "$CHANGED_FILES" | grep -E '^lambda/landing/'; then
          echo "landing_lambda_changed=true" >> $GITHUB_OUTPUT
          echo "✅ Landing Lambda changed"
        else
          echo "landing_lambda_changed=false" >> $GITHUB_OUTPUT
        fi

        # Global UI changes (shared scripts)
        if echo "$CHANGED_FILES" | grep -E '^(scripts/generate-architecture-diagram\.py|scripts/deploy-ui\.sh)'; then
          echo "ui=true" >> $GITHUB_OUTPUT
          echo "✅ Global UI scripts changed"
        else
          echo "ui=false" >> $GITHUB_OUTPUT
        fi

        # Per-vertical UI changes
        if echo "$CHANGED_FILES" | grep -E '^ui-insurance/'; then
          echo "insurance_ui_changed=true" >> $GITHUB_OUTPUT
          echo "✅ Insurance UI changed"
        else
          echo "insurance_ui_changed=false" >> $GITHUB_OUTPUT
        fi

        if echo "$CHANGED_FILES" | grep -E '^ui-retail/'; then
          echo "retail_ui_changed=true" >> $GITHUB_OUTPUT
          echo "✅ Retail UI changed"
        else
          echo "retail_ui_changed=false" >> $GITHUB_OUTPUT
        fi

        if echo "$CHANGED_FILES" | grep -E '^ui-healthcare/'; then
          echo "healthcare_ui_changed=true" >> $GITHUB_OUTPUT
          echo "✅ Healthcare UI changed"
        else
          echo "healthcare_ui_changed=false" >> $GITHUB_OUTPUT
        fi

        if echo "$CHANGED_FILES" | grep -E '^ui-landing/'; then
          echo "landing_ui_changed=true" >> $GITHUB_OUTPUT
          echo "✅ Landing UI changed"
        else
          echo "landing_ui_changed=false" >> $GITHUB_OUTPUT
        fi

        # Test changes
        if echo "$CHANGED_FILES" | grep -E '^(tests/e2e/|\.github/workflows/)'; then
          echo "tests=true" >> $GITHUB_OUTPUT
          echo "✅ Test files changed"
        else
          echo "tests=false" >> $GITHUB_OUTPUT
          echo "ℹ️ No test changes"
        fi
