name: Setup Infrastructure Deployment
description: Complete setup for CDK infrastructure deployment (Python, dependencies, AWS credentials, CDK)

inputs:
  aws-role-arn:
    description: 'AWS IAM role ARN to assume for deployment'
    required: true
  aws-region:
    description: 'AWS region for deployment'
    required: false
    default: 'us-east-1'

runs:
  using: composite
  steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: requirements-test.txt

    - name: Install dependencies
      uses: ./.github/actions/install-deps
      with:
        install-ui: 'false'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup AWS CDK
      uses: ./.github/actions/setup-aws-cdk

    - name: Bootstrap CDK
      uses: ./.github/actions/bootstrap-cdk
